name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: create build
      run: mkdir -p build
    
    - name: install lcov
      run: sudo apt update && sudo apt install -y lcov

    - name: run command
      run: |
        cd build
        cmake -G "Unix Makefiles" ..
        make 

    - name: clang-tidy
      run: |
        cd build
        clang-tidy -p=compile_commands.json ../src/*.cpp

    - name: run test
      run: |
        cd build
        ctest -V

    - name: coverage
      run: |
        cd build
        lcov --directory . --capture --ignore-errors mismatch --output-file coverage.info
        lcov --list coverage.info
        lcov --remove coverage.info '*/test/*' '*/_deps/*' '/usr/*' --ignore-errors unused --output-file coverage_filtered.info
        lcov --list coverage_filtered.info

  docker-build:
    needs: build 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: log
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: build
      run: |
        OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        IMAGE_NAME="ghcr.io/${OWNER}/my-app"
        docker build -t $IMAGE_NAME .
        docker push $IMAGE_NAME
    